name: lemondoro
description: "A Pomodoro app with a lemonade theme to enhance your productivity."

version: 1.0.0+1

environment:
  sdk: '>=3.2.0-78.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  liquid_progress_indicator_v2: ^0.5.0
  
  provider: ^6.1.2
  audioplayers: ^5.1.0
  shared_preferences: ^2.2.0
  
flutter_icons:
  android: true
  ios: true
  image_path: assets/image/app_icon.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#fff9cf"
  image: assets/image/app_icon.png 
  android: true
  ios: true

flutter:
  
  uses-material-design: true
  assets:
    - assets/sound/alarm/
    - assets/sound/Drip.wav
    - assets/sound/Slurp.wav
    - assets/sound/Squeeze.wav
    - assets/image/
  
  fonts:
    - family: Kanit
      fonts:
        - asset: assets/font/Kanit-Regular.ttf
    - family: Nunito
      fonts:
        - asset: assets/font/Nunito-Regular.ttf
        - asset: assets/font/Nunito-Bold.ttf
          weight: 700